[package]
name = "paste"
version = "0.1.0"
authors = ["slerpy <48803074+slerpyyy@users.noreply.github.com>"]
edition = "2018"

[profile.release]
opt-level = 3
lto = true
panic = "abort"

[dependencies]
noisy_float = "0.1.12"
pico-args = "0.3.4"
